--
-- File generated with SQLiteStudio v3.3.3 on qui out 27 14:54:42 2022
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: TBADMISSAO_MEMBRO
CREATE TABLE TBADMISSAO_MEMBRO (ID INTEGER PRIMARY KEY AUTOINCREMENT, DESCRICAO VARCHAR (150));

-- Table: TbCargo
CREATE TABLE TbCargo (ID INTEGER PRIMARY KEY AUTOINCREMENT, DESCRICAO VARCHAR (150));

-- Table: TBCARGO_MEMBRO
CREATE TABLE TBCARGO_MEMBRO (ID INTEGER PRIMARY KEY AUTOINCREMENT, IDCARGO INTEGER REFERENCES TbCargo (ID) ON DELETE CASCADE, IDMEMBRO INTEGER REFERENCES TbMembros (ID) ON DELETE CASCADE, DTINICIO DATE, DTFIM DATE);

-- Table: TBCAT_ENTRADA
CREATE TABLE TBCAT_ENTRADA (ID INTEGER PRIMARY KEY AUTOINCREMENT, DESCRICAO VARCHAR (150));

-- Table: TBCAT_SAIDA
CREATE TABLE TBCAT_SAIDA (ID INTEGER PRIMARY KEY AUTOINCREMENT, DESCRICAO VARCHAR (150));

-- Table: TBENTRADA
CREATE TABLE TBENTRADA (ID INTEGER PRIMARY KEY AUTOINCREMENT, IDCAT_ENTRADA INTEGER REFERENCES TBCAT_ENTRADA (ID) ON DELETE SET NULL, IDMEMBRO INTEGER REFERENCES TbMembros (ID) ON DELETE SET NULL, DATA DATE, OBS VARCHAR (150), VALOR DECIMAL (10, 2));

-- Table: TBHISTORICO
CREATE TABLE TBHISTORICO (ID INTEGER PRIMARY KEY AUTOINCREMENT, IDMEMBRO INTEGER REFERENCES TbMembros (id) ON DELETE CASCADE, DATA DATE, DESCRICAO VARCHAR (150));

-- Table: TbIgreja
CREATE TABLE TbIgreja (Nome VARCHAR (250), Endereco VARCHAR (250), Bairro VARCHAR (250), Cidade VARCHAR (250), Tel1 VARCHAR (20), Tel2 VARCHAR (20), UF VARCHAR (2), Email VARCHAR (150), CEP VARCHAR (10), CNPJ VARCHAR (18), Sede VARCHAR (250), SaldoInicial DECIMAL (10, 2), Tit1 VARCHAR (150), Assinatura1 VARCHAR (250), Tit2 VARCHAR (150), Assinatura2 VARCHAR (250));

-- Table: TbMembros
CREATE TABLE TbMembros (ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, NOME VARCHAR (250), DTNASC DATE, CPF VARCHAR (11), RG VARCHAR (20), SEXO VARCHAR (3), ENDERECO VARCHAR (250), BAIRRO VARCHAR (150), CIDADE VARCHAR (250), CEP VARCHAR (8), UF VARCHAR (2), TEL1 VARCHAR (11), TEL2 VARCHAR (11), EMAIL VARCHAR (150), DTMEMBRO DATE, DTCASAMENTO DATE, NOME_PAI VARCHAR (250), NOME_MAE VARCHAR (250), ESTADO_CIVIL VARCHAR (50), TIT_ELEITOR VARCHAR (30), OBS VARCHAR (500), PROFISSAO VARCHAR (150), LOCAL_NASCIMENTO VARCHAR (150), PROCEDENCIA VARCHAR (150), IDADMISSAO INTEGER REFERENCES TBADMISSAO_MEMBRO (ID), IDSITUACAO INTEGER REFERENCES TBSITUACAO_MEMBRO (ID), INATIVO BOOLEAN DEFAULT (0));

-- Table: TBSAIDA
CREATE TABLE TBSAIDA (ID INTEGER PRIMARY KEY AUTOINCREMENT, IDCAT_SAIDA INTEGER REFERENCES TBCAT_SAIDA (ID) ON DELETE SET NULL, DATA DATE, VALOR DECIMAL (10, 2), OBS VARCHAR (150));

-- Table: TBSITUACAO_MEMBRO
CREATE TABLE TBSITUACAO_MEMBRO (ID INTEGER PRIMARY KEY AUTOINCREMENT, DESCRICAO VARCHAR (150));

-- Table: TbUsuarios
CREATE TABLE TbUsuarios (id INTEGER PRIMARY KEY AUTOINCREMENT, user VARCHAR (50), senha VARCHAR (50), usuarios BOOLEAN, membros BOOLEAN, lanc BOOLEAN, vis BOOLEAN, cargos BOOLEAN, dadosIgreja BOOLEAN, ebd BOOLEAN);

-- Table: TBVISITANTES
CREATE TABLE TBVISITANTES (ID INTEGER PRIMARY KEY AUTOINCREMENT, NOME VARCHAR (250), DTNASC DATE, SEXO VARCHAR (3), ENDERECO VARCHAR (150), BAIRRO VARCHAR (150), CIDADE VARCHAR (150), CEP VARCHAR (8), UF VARCHAR (2), TEL1 VARCHAR (11), TEL2 VARCHAR (11), EMAIL VARCHAR (150), DTCASAMENTO DATE, ESTADO_CIVIL VARCHAR (15), OBS VARCHAR (250), PROFISSAO VARCHAR (50), LOCAL_NASCIMENTO VARCHAR (150));

-- Table: TBVISITAS
CREATE TABLE TBVISITAS (ID INTEGER PRIMARY KEY AUTOINCREMENT, IDVISITANTE INTEGER REFERENCES TBVISITANTES (ID) ON DELETE CASCADE, DATA DATE, TIPO VARCHAR (150), OBS VARCHAR (250));

-- View: VWCARGOS_OCUPADOS
CREATE VIEW VWCARGOS_OCUPADOS AS SELECT CM.ID, C.DESCRICAO, M.NOME AS MEMBRO, CM.DTINICIO, CM.DTFIM

FROM TbCargo C
INNER JOIN TBCARGO_MEMBRO CM
    ON CM.IDCARGO = C.ID
INNER JOIN TbMembros M 
    ON CM.IDMEMBRO = M.ID;

-- View: VWENTRADAS
CREATE VIEW VWENTRADAS AS SELECT 
    E.ID, E.DATA, E.IDCAT_ENTRADA, E.OBS, E.VALOR,
    M.NOME AS MEMBRO, C.DESCRICAO
FROM TBENTRADA E
LEFT JOIN TbMembros M
    ON E.IDMEMBRO = M.ID
LEFT JOIN TBCAT_ENTRADA C
    ON E.IDCAT_ENTRADA = C.ID;

-- View: VWMEMBROS
CREATE VIEW VWMEMBROS AS SELECT M.Id as ID, M.NOME, M.DTNASC, M.SEXO, M.ESTADO_CIVIL, M.DTMEMBRO, M.INATIVO,
    M.CPF, M.RG, M.TIT_ELEITOR, M.ENDERECO, M.BAIRRO, M.CIDADE, M.UF, M.CEP, M.TEL1, M.TEL2, M.EMAIL, M.DTCASAMENTO, M.ESTADO_CIVIL,
    M.NOME_PAI, M.NOME_MAE, M.PROFISSAO, M.OBS, M.LOCAL_NASCIMENTO, M.PROCEDENCIA,
    A.ID AS IDADM, A.DESCRICAO AS ADMISSAO,
    S.ID AS IDSIT, S.DESCRICAO as SITUACAO

FROM TbMembros M
    LEFT JOIN TBADMISSAO_MEMBRO A
        ON M.IDADMISSAO = A.ID
    LEFT JOIN TBSITUACAO_MEMBRO S
        ON M.IDSITUACAO = S.ID;

-- View: VWSAIDAS
CREATE VIEW VWSAIDAS AS SELECT 
    S.ID,  S.DATA, S.VALOR, S.OBS, C.DESCRICAO
FROM TBSAIDA S
LEFT JOIN TBCAT_SAIDA C
    ON S.IDCAT_SAIDA = C.ID;

-- View: VWVISITANTES
CREATE VIEW VWVISITANTES AS SELECT 
    ID, NOME, DTNASC, 
    (SELECT DATA FROM TBVISITAS VTA WHERE VTA.IDVISITANTE = VTE.ID ORDER BY DATA DESC LIMIT 1) AS VISITADO,
    (SELECT COUNT (DATA) FROM TBVISITAS VTA WHERE VTA.IDVISITANTE = VTE.ID AND TIPO = 'RECEBIDA') AS RECEBIDAS,
    (SELECT COUNT (DATA) FROM TBVISITAS VTA WHERE VTA.IDVISITANTE = VTE.ID AND TIPO = 'REALIZADA') AS REALIZADAS
FROM TBVISITANTES VTE;

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
